
'use server';

/**
 * @fileOverview An AI agent to perform patent searches and generate a novelty report.
 *
 * - patentSearch - A function that handles the patent search and analysis process.
 * - PatentSearchInput - The input type for the patentSearch function.
 * - PatentSearchOutput - The return type for the patentSearch function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Input Schema: The user provides a description of their invention.
export const PatentSearchInputSchema = z.object({
  inventionDescription: z.string().describe('A detailed description of the user\'s invention, including its purpose, components, and method of operation.'),
});
export type PatentSearchInput = z.infer<typeof PatentSearchInputSchema>;


// Output Schema: The structured report generated by the AI.
const PriorArtSchema = z.object({
    patentId: z.string().describe('The ID number of the prior art patent (e.g., "US 9,123,456 B2").'),
    title: z.string().describe('The title of the patent.'),
    url: z.string().describe('A URL to view the full patent document.'),
    publicationDate: z.string().describe('The date the patent was published.'),
    relevanceScore: z.number().min(0).max(100).describe('A score from 0-100 indicating how relevant this patent is to the user\'s invention.'),
    summary: z.string().describe('A brief summary of what the patent covers.'),
    noveltyComparison: z.string().describe('A specific analysis of how the user\'s invention differs from or is similar to this patent, highlighting potential novelty issues.'),
});

export const PatentSearchOutputSchema = z.object({
  reportSummary: z.string().describe('A high-level summary of the search findings, including an overall assessment of the invention\'s potential patentability.'),
  priorArt: z.array(PriorArtSchema).describe('A ranked list of the most relevant prior art patents found.'),
  keyTechnicalConcepts: z.array(z.string()).describe('A list of key technical terms and concepts identified in the search space.'),
  recommendations: z.string().describe('Next steps and strategic recommendations for the user (e.g., "Consider focusing on X novel feature," "Consult with a patent attorney").'),
});
export type PatentSearchOutput = z.infer<typeof PatentSearchOutputSchema>;


export async function patentSearch(input: PatentSearchInput): Promise<PatentSearchOutput> {
  return patentSearchFlow(input);
}


// 1. Define a tool to search a patent database.
// This simulates calling an external API like Google Patents or a private database.
const searchPatentsTool = ai.defineTool(
  {
    name: 'searchPatents',
    description: 'Searches a database of existing patents for documents relevant to a given invention description. Returns a list of patent documents with summaries.',
    inputSchema: z.object({
      query: z.string().describe('A search query derived from the user\'s invention description, focusing on key technical features.'),
    }),
    outputSchema: z.object({
      results: z.array(z.object({
        patentId: z.string(),
        title: z.string(),
        url: z.string(),
        publicationDate: z.string(),
        abstract: z.string(),
      })),
    }),
  },
  async (input) => {
    // In a real application, this would make an API call to a patent database.
    // For this example, we return realistic mock data based on the query.
    console.log(`Tool "searchPatents" called with query: ${input.query}`);
    if (input.query.toLowerCase().includes('drone' || 'delivery')) {
       return {
            results: [
                {
                    patentId: 'US 10,987,654 B2',
                    title: 'Autonomous Drone Delivery System with Secure Payload Release',
                    url: 'https://patents.google.com/patent/US10987654B2/en',
                    publicationDate: '2021-05-18',
                    abstract: 'A system and method for autonomous aerial delivery of payloads. Drones navigate to a destination and use a secure, authenticated mechanism to release a payload container. The system includes features for obstacle avoidance and real-time route adjustment based on weather data.'
                },
                 {
                    patentId: 'US 9,123,456 B1',
                    title: 'Method for Coordinating a Fleet of Delivery Vehicles',
                    url: 'https://patents.google.com/patent/US9123456B1/en',
                    publicationDate: '2015-11-03',
                    abstract: 'A central server coordinates a fleet of delivery vehicles (ground-based or aerial) to optimize delivery routes. It allocates tasks based on vehicle location, capacity, and delivery deadlines, using a predictive model to estimate travel times.'
                }
            ]
        }
    }
    return { results: [] };
  }
);


// 2. Define the main prompt that uses the tool to generate the report.
const patentSearchPrompt = ai.definePrompt({
  name: 'patentSearchPrompt',
  tools: [searchPatentsTool],
  input: { schema: PatentSearchInputSchema },
  output: { schema: PatentSearchOutputSchema },
  prompt: `You are a world-class patent analyst AI. Your task is to conduct a thorough prior art search based on the user's invention description and generate a structured Patent Search Report.

**User's Invention:**
---
{{{inventionDescription}}}
---

**Instructions:**
1.  **Formulate Search Query**: Based on the invention description, formulate a precise search query highlighting the key technical features and concepts.
2.  **Conduct Search**: Use the \`searchPatents\` tool to find relevant prior art. You may need to call it more than once with refined queries to get the best results.
3.  **Analyze and Rank Results**: Review the search results. For each relevant patent, you must:
    a.  **Assess Relevance**: Assign a relevance score from 0-100 indicating how closely it relates to the user's invention.
    b.  **Summarize**: Write a concise summary of the patent's abstract.
    c.  **Perform Novelty Comparison**: This is the most critical step. Directly compare the prior art to the user's invention. Clearly state what is similar and, more importantly, what appears to be novel or different in the user's invention compared to this specific patent.
4.  **Synthesize Final Report**: Compile your findings into the final structured report.
    a.  **Report Summary**: Write a high-level overview of your findings and give an initial assessment of the invention's patentability.
    b.  **Prior Art List**: Create the ranked list of the most relevant prior art you analyzed.
    c.  **Key Concepts**: List the key technical terms you identified.
    d.  **Recommendations**: Provide actionable next steps for the user. Do not give legal advice, but suggest areas of focus or consultation with a patent attorney.

Your entire output must strictly follow the defined JSON schema. Do not invent patents; rely only on the information provided by the \`searchPatents\` tool.`,
});


// 3. Define the flow that orchestrates the prompt and tool.
const patentSearchFlow = ai.defineFlow(
  {
    name: 'patentSearchFlow',
    inputSchema: PatentSearchInputSchema,
    outputSchema: PatentSearchOutputSchema,
  },
  async (input) => {
    const { output } = await patentSearchPrompt(input);
    if (!output) {
      throw new Error('The model did not return a valid patent search report.');
    }
    return output;
  }
);
