'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileDown, Printer, Copy } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ReportDisplayProps {
  report: string;
  query: string;
}

export function ReportDisplay({ report, query }: ReportDisplayProps) {
  const { toast } = useToast();

  const handleDownload = () => {
    const blob = new Blob([`Query:\n${query}\n\nReport:\n${report}`], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'IndiLaw-AI-Report.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(report).then(() => {
      toast({ title: "Report copied to clipboard!" });
    }, () => {
      toast({ variant: "destructive", title: "Failed to copy report" });
    });
  };

  const handlePrint = () => {
    const printableContent = `
      <html>
        <head>
          <title>IndiLaw AI Research Report</title>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'PT Sans', sans-serif; line-height: 1.6; color: #333; }
            h1, h2, h3 { font-family: 'Playfair Display', serif; color: #003366; }
            pre { white-space: pre-wrap; word-wrap: break-word; font-family: 'PT Sans', sans-serif; }
            @page { size: A4; margin: 1in; }
          </style>
        </head>
        <body>
          <h1>IndiLaw AI Research Report</h1>
          <h2>Query:</h2>
          <p>${query}</p>
          <hr />
          <h2>Generated Report:</h2>
          <pre>${report}</pre>
        </body>
      </html>
    `;
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printableContent);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  return (
    <Card className="shadow-lg animate-in fade-in-50">
      <CardHeader>
        <div className="flex justify-between items-start flex-wrap gap-4">
            <div>
                <CardTitle className="font-headline text-2xl">Legal Research Report</CardTitle>
                <CardDescription>Generated by IndiLaw AI for your query.</CardDescription>
            </div>
            <div className="flex items-center gap-2">
                <Button variant="ghost" size="icon" onClick={handleCopy} aria-label="Copy Report">
                    <Copy className="h-4 w-4" />
                </Button>
                <Button variant="ghost" size="icon" onClick={handlePrint} aria-label="Print Report">
                    <Printer className="h-4 w-4" />
                </Button>
                <Button onClick={handleDownload}>
                    <FileDown className="mr-2 h-4 w-4" />
                    Download
                </Button>
            </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="prose prose-sm max-w-none rounded-md border bg-muted/30 p-4 h-[60vh] overflow-y-auto">
            <pre className="whitespace-pre-wrap font-body text-sm">{report}</pre>
        </div>
      </CardContent>
    </Card>
  );
}
